FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /work/
RUN chmod 775 /work/wait-for-it.sh
EXPOSE 8080
CMD ["./wait-for-it.sh", "db:5432", "--", "./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.datasource.url=jdbc:postgresql://db:5432/quarkus"]
